package com.obra.obra.entities;

public enum CategoriaOrcamento {
    FUNDACAO,
    ESTRUTURA,
    ALVENARIA,
    COBERTURA,
    ESQUADRIAS,
    INSTALACOES_ELETRICAS,
    INSTALACOES_HIDRAULICAS,
    REVESTIMENTOS,
    ACABAMENTOS,
    LOUCAS_E_METAIS,
    MATERIAIS_BASICOS,
    IMPERMEABILIZACAO,
    VIDROS,
    MARCENARIA,
    GESSO_E_DRYWALL,
    PAISAGISMO,
    MAO_DE_OBRA,
    EQUIPAMENTOS_E_FERRAMENTAS,
    FRETE_E_LOGISTICA,
    SERVICOS_TERCEIRIZADOS
}
